### ISSUE TITLE
Could not load file or assembly 'ICSharpCode.SharpZipLib 

### ISSUE THREAD

**Issue by zh3305** [rukpat/PDFPasswordRemover#1]
install  [PDFPasswordRemoverWinx64Installer.exe](https://github.com/rukpat/PDFPasswordRemover/releases/download/v1.0.0/PDFPasswordRemoverWinx64Installer.exe)
then run
```
Enter the password for the PDF files:
Overwrite mode DISABLED. Files will be prefixed with '_decrypted'.

EXCEPTION: E800-DTU(Z2530-ETH-27)_UserManual_CN_v1.0.pdf (Exception Details: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=1.3.3.11, Culture=neutral, PublicKeyToken=1b03e6acf1164f73'. 系统找不到指定的文件。)

All PDF files processed!
Press ENTER key to continue...

```
![image](https://github.com/user-attachments/assets/6bdc1355-c391-4aea-9b69-bd645b6946f6)

**Comment by rukpat** [comment]
Installing ICSharpCode.SharpZipLib in Visual Studio
Using NuGet Package Manager:
 * Open your Visual Studio project.
 * Right-click on your project in the Solution Explorer and select "Manage
NuGet Packages."
 * Search for "SharpZipLib" in the search bar.
 * Select the desired version (in your case, 1.3.3.11) from the search
results.
 * Click "Install."
Using the Package Manager Console:
 * Open the Package Manager Console from the Tools menu in Visual Studio.
 * Execute the following command:
   Install-Package ICSharpCode.SharpZipLib -Version 1.3.3.11

Manual Installation:
 * Download the NuGet package for the desired version from the NuGet
website.
 * Extract the downloaded package.
 * Add a reference to the ICSharpCode.SharpZipLib.dll file in your project:
   * Right-click on your project in the Solution Explorer and select "Add
Reference."
   * Browse to the extracted DLL file and add it.
Using the .NET CLI:
 * Open a command prompt or terminal window.
 * Navigate to your project's directory.
 * Execute the following command:
   dotnet add package ICSharpCode.SharpZipLib --version 1.3.3.11

Additional Considerations:
 * Version Compatibility: Ensure that the version you choose is compatible
with your project's target framework.
 * Namespace Usage: Once installed, you can use the library by adding the
following namespace to your code:
   using ICSharpCode.SharpZipLib.Zip;

 * Error Handling: Implement appropriate error handling mechanisms to
handle potential exceptions during ZIP operations.
By following these steps, you should be able to successfully install and
use the ICSharpCode.SharpZipLib library in your Visual Studio project.

**Comment by rukpat** [comment]
> install  [PDFPasswordRemoverWinx64Installer.exe](https://github.com/rukpat/PDFPasswordRemover/releases/download/v1.0.0/PDFPasswordRemoverWinx64Installer.exe)
> then run
> ```
> Enter the password for the PDF files:
> Overwrite mode DISABLED. Files will be prefixed with '_decrypted'.
> 
> EXCEPTION: E800-DTU(Z2530-ETH-27)_UserManual_CN_v1.0.pdf (Exception Details: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=1.3.3.11, Culture=neutral, PublicKeyToken=1b03e6acf1164f73'. 系统找不到指定的文件。)
> 
> All PDF files processed!
> Press ENTER key to continue...
> 
> ```
> ![image](https://github.com/user-attachments/assets/6bdc1355-c391-4aea-9b69-bd645b6946f6)
> 

You are missing the library:

Install as follows:

Installing ICSharpCode.SharpZipLib in Visual Studio
Using NuGet Package Manager:
 * Open your Visual Studio project.
 * Right-click on your project in the Solution Explorer and select "Manage NuGet Packages."
 * Search for "SharpZipLib" in the search bar.
 * Select the desired version (in your case, 1.3.3.11) from the search results.
 * Click "Install."
Using the Package Manager Console:
 * Open the Package Manager Console from the Tools menu in Visual Studio.
 * Execute the following command:
   Install-Package ICSharpCode.SharpZipLib -Version 1.3.3.11

Manual Installation:
 * Download the NuGet package for the desired version from the NuGet website.
 * Extract the downloaded package.
 * Add a reference to the ICSharpCode.SharpZipLib.dll file in your project:
   * Right-click on your project in the Solution Explorer and select "Add Reference."
   * Browse to the extracted DLL file and add it.
Using the .NET CLI:
 * Open a command prompt or terminal window.
 * Navigate to your project's directory.
 * Execute the following command:
   dotnet add package ICSharpCode.SharpZipLib --version 1.3.3.11

Additional Considerations:
 * Version Compatibility: Ensure that the version you choose is compatible with your project's target framework.
 * Namespace Usage: Once installed, you can use the library by adding the following namespace to your code:
   using ICSharpCode.SharpZipLib.Zip;

 * Error Handling: Implement appropriate error handling mechanisms to handle potential exceptions during ZIP operations.
By following these steps, you should be able to successfully install and use the ICSharpCode.SharpZipLib library in your Visual Studio project.


If you are using something else. Please ask your favourite GenAI.

**Comment by zh3305** [comment]
> > install  [PDFPasswordRemoverWinx64Installer.exe](https://github.com/rukpat/PDFPasswordRemover/releases/download/v1.0.0/PDFPasswordRemoverWinx64Installer.exe)
> > then run
> > ```
> > Enter the password for the PDF files:
> > Overwrite mode DISABLED. Files will be prefixed with '_decrypted'.
> > 
> > EXCEPTION: E800-DTU(Z2530-ETH-27)_UserManual_CN_v1.0.pdf (Exception Details: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=1.3.3.11, Culture=neutral, PublicKeyToken=1b03e6acf1164f73'. 系统找不到指定的文件。)
> > 
> > All PDF files processed!
> > Press ENTER key to continue...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/6190168/386494325-6bdc1355-c391-4aea-9b69-bd645b6946f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5OTcxMDMsIm5iZiI6MTczMzk5NjgwMywicGF0aCI6Ii82MTkwMTY4LzM4NjQ5NDMyNS02YmRjMTM1NS1jMzkxLTRhZWEtOWI2OS1iZDY0NWI2OTQ2ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMDk0NjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2NiMDk0YmI3Mjk4M2YwOTA3NjI5ZDhhOTMyZDAzNmQ4MTNkNjNjN2MwNjBkYTY4NDdiMGM1NDYwNGY5MThhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wOrmLuGH16dcUqeepiomhz6g05szOs8JDSyMdhTBGGU)
> 
> You are missing the library:
> 
> Install as follows:
> 
> Installing ICSharpCode.SharpZipLib in Visual Studio Using NuGet Package Manager:
> 
> * Open your Visual Studio project.
> * Right-click on your project in the Solution Explorer and select "Manage NuGet Packages."
> * Search for "SharpZipLib" in the search bar.
> * Select the desired version (in your case, 1.3.3.11) from the search results.
> * Click "Install."
>   Using the Package Manager Console:
> * Open the Package Manager Console from the Tools menu in Visual Studio.
> * Execute the following command:
>   Install-Package ICSharpCode.SharpZipLib -Version 1.3.3.11
> 
> Manual Installation:
> 
> * Download the NuGet package for the desired version from the NuGet website.
> * Extract the downloaded package.
> * Add a reference to the ICSharpCode.SharpZipLib.dll file in your project:
>   
>   * Right-click on your project in the Solution Explorer and select "Add Reference."
>   * Browse to the extracted DLL file and add it.
>     Using the .NET CLI:
> * Open a command prompt or terminal window.
> * Navigate to your project's directory.
> * Execute the following command:
>   dotnet add package ICSharpCode.SharpZipLib --version 1.3.3.11
> 
> Additional Considerations:
> 
> * Version Compatibility: Ensure that the version you choose is compatible with your project's target framework.
> * Namespace Usage: Once installed, you can use the library by adding the following namespace to your code:
>   using ICSharpCode.SharpZipLib.Zip;
> * Error Handling: Implement appropriate error handling mechanisms to handle potential exceptions during ZIP operations.
>   By following these steps, you should be able to successfully install and use the ICSharpCode.SharpZipLib library in your Visual Studio project.
> 
> If you are using something else. Please ask your favourite GenAI.

Thank you. This method has been solved.
